### ISSUE TITLE
unmatched PE reads counts after dereplicate and normalize

### ISSUE THREAD

**Issue by jingzhejiang** [cmmr/virmap#15]
Hi,

I tried to assamble 7 libraries using virmap.
Only 3 of them have results after megahit assembly step:

-rw-rw-r-- 1 ubuntu ubuntu       0 Sep 28 04:31 S1/S1.contigs.fa
-rw-rw-r-- 1 ubuntu ubuntu  204113 Sep 28 03:29 S2/S2.contigs.fa
-rw-rw-r-- 1 ubuntu ubuntu 2733672 Sep 28 04:26 S3/S3.contigs.fa
-rw-r--r-- 1 ubuntu ubuntu  341697 Sep 29 21:20 S4/S4.contigs.fa
-rw-rw-r-- 1 ubuntu ubuntu       0 Sep 28 04:26 S5/S5.contigs.fa
-rw-r--r-- 1 ubuntu ubuntu       0 Sep 29 00:22 S6/S6.contigs.fa
-rw-r--r-- 1 ubuntu ubuntu       0 Sep 30 02:18 S7/S7.contigs.fa

The other four libraries reported with a same error (unmatched PE reads counts). I think this maybe because the dereplicate or normalize step filtrated unequal number of reads from raw PE reads.
How should I solve this problem?

Thank you!

**Comment by torptube** [comment]
The normalization and dereplication steps shouldn't affect megahit's inputs. Are your read1 and read2 files balanced going into virmap? Can you post line counts for the input fastqs for S1?

**Comment by jingzhejiang** [comment]
Thank you for your reply!!
I think you are right! My read1 and read2 files were not balanced going into virmap.
Thank you!
